
###
# IOT DEVIES
POST http://localhost:3000/api/auth/device/login/ HTTP/1.1
Content-Type: application/json

{
    "id":"4249266a-774a-4fa3-b410-0aa25360be31","password":"12345678"
}


###
# Users App 
POST http://localhost:3000/api/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"princ@me.us","password":"password123"
}

###
POST http://localhost:3000/api/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"me@yu.us","password":"12345678"
}

###
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "me@yu.us",
    "password": "12345678",
    "name": "yu"
}

