
###
# IOT DEVIES
POST http://localhost/api/auth/device/login/ HTTP/1.1
Content-Type: application/json

{
    "id":"5682e637-2f29-403f-8383-4b8f3f6b2f82","password":"12345678"
}


###
# Users App 
POST http://localhost:80/api/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"princ@me.us","password":"password123"
}

###
POST http://localhost:80/api/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"me@yu.us","password":"12345678"
}

###
POST http://localhost:80/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "me@yu.us",
    "password": "12345678",
    "name": "yu"
}

